geolocation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('location.urls'))
]

location/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static  


app_name = "ubicacion_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name='Inicio'),
    path('ubicacion_actual/', views.ubicacion, name='ubicacion-actual'),
    path('registros-delitos/',views.ListAllZonas.as_view(),name='zonas_all'),
    path('registros-segura/', views.ListSegura.as_view(), name='zona_segura'),
    path('registros-insegura/', views.ListInsegura.as_view(), name='zona_insegura'),
    path('registros-delictiva/', views.ListDelictiva.as_view(), name='zona_delictiva'),
    # Clase para poder ver los delitos
    path("ver-delitos/<str:codigo_postal>/", views.DelitosPorCodigoPostalView.as_view(), name="delitos-registros"),
    path("update-zona/<str:codigo_postal>/", views.ZonaModUpdateView.as_view(), name = 'zona-modificada'),
    path("estado-seguridad/", views.estado_seguridad, name='estado-seguridad'),
    # Formulario para registrar un delito
    path('registrar-delito/', views.RegistrarDelitoView.as_view(), name='registrar_delito'),
    path('borrar-delito/<int:pk>/', views.DelitoDeleteView.as_view(), name="borrar-delito"), 
    path('registro-ratero/', views.RegistrarRateroView.as_view(), name='agregar-ratero'),
    path('ver-ratero/<str:codigo_postal>/', views.DelincuentesPorCodigoPostalView.as_view(), name='detalles-ratero'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

location/models.py
from django.db import models

# Create your models here.

class Ubicacion(models.Model):

    SEGURIDAD_CHOICES = [
        ('0', 'segura'),
        ('1', 'insegura'),
        ('2', 'zona delictiva'),
    ]
    
    codigo_postal = models.CharField("Código postal", max_length=10, unique=False)
    nombre_ciudad = models.CharField("Nombre de la ciudad", max_length=50)
    nombre_colonia = models.CharField("Nombre de la colonia", max_length=70)
    seguridad_zona = models.CharField(
        "Seguridad de la zona", 
        max_length=1,
        choices=SEGURIDAD_CHOICES, 
        default='0'
    )

    class Meta:
        verbose_name = "Dato de seguimiento"
        verbose_name_plural = "Datos de seguimiento"

    def __str__(self):
        return self.codigo_postal


class Delito(models.Model):
    TIPO_DELITO = [
        ('0', 'robo'),
        ('1', 'asalto'),
        ('2', 'abuso'),
        ('3', 'venta de drogas'),
        ('4', 'homicidio'),
        ('5', 'secuestro'),
        ('6', 'feminicidio'),
    ]
    
    codigop_delito = models.ForeignKey(Ubicacion, on_delete=models.CASCADE) 
    delegacion_delito = models.CharField("Delegación del delito", max_length=30)
    calle_delito = models.CharField("Calle del delito", max_length=30)
    colonia_delito = models.CharField("Colonia del delito", max_length=30)
    tipo_delito = models.CharField(
        "Tipo de Delito", 
        max_length=1,
        choices=TIPO_DELITO, 
        default='0'
    )
    
    descripcion = models.TextField("Descripción del delito", blank=True) #La persona podrá agregar una descripción del delito.

    class Meta:
        verbose_name = "Registro de delito"
        verbose_name_plural = "Registros de delitos"

    def __str__(self):
        return self.codigop_delito.codigo_postal

class Delincuente(models.Model):

    codigop_delincuente = models.ForeignKey(Ubicacion,on_delete=models.CASCADE) 
    nombre_delincuente = models.CharField("Nombre del delincuente", max_length=40)
    proceso = models.CharField("¿Se encuentra en proceso el delincuente?", max_length=100)
    avatar = models.ImageField("Imagen del delincuente",upload_to='media/delincuente', blank = True, null = True) #Aqui se guardará la IMAGEN.
    descripcion_delincuente = models.TextField("Describe las características del delincuente", blank=True) #La persona podrá agregar una descripción del delito.
   
    class Meta:
        verbose_name = "Datos de delicuente"
        verbose_name_plural = "Datos de los delincuentes"

    def __str__(self):
        return self.codigop_delincuente.codigo_postal   

templates/templates-generales/delito.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Registro de delitos en {{ ubicacion.codigo_postal }}{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="cell text-center">
    <h1>Delitos en {{ ubicacion.nombre_colonia }}, {{ ubicacion.nombre_ciudad }} ({{ ubicacion.codigo_postal }})</h1>
    <table class="grid-container">
        <thead>
         <tr>
          <th width="150">Delegación</th>
          <th width="300">Calle</th>
          <th width="300">Colonia</th>
          <th width="150">Código Postal</th>
          <th width="150">Delito</th>
          {% comment %} <th width="250">Detalles del delito</th> {% endcomment %}
          <th width="100">Borrar delito</th>
        </tr>
        
        </thead>
        <tbody>
         {% for e in delitos %}
         <!-- cada tr es una fila de la tabla -->
          <tr>
           <td>{{ e.delegacion_delito }}</td>
           <td>{{ e.calle_delito }}</td>
           <td>{{ e.colonia_delito }}</td>
           <td>{{ e.codigop_delito.codigo_postal }}</td>
           <td>{{ e.get_tipo_delito_display }}</td>
           <td><a class="button alert" href="{% url 'ubicacion_app:borrar-delito' e.id %}">Borrar delito</a></td>
        </tr>
         {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

templates/templates-generales/inicio.html
{% extends 'base.html'%}

{% load static %}

{% block title %} Pagina de inicio al sistema UniSecure {% endblock title %}

{% block content %}

{% include 'includes/header.html' %}


<div class="pantalla margin-top">
  <!-- inicio de la imagen de portada -->
  <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
    <div class="orbit-wrapper">
      <div class="orbit-controls"> 
        <!-- En esta parte estamos definiendo los botones de antes y después de nuestros slides -->
        <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
        <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
      </div>

      <ul class="orbit-container">
        <li class="is-active orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static 'img/FotoRepuestoSildeDos.jpg' %}" alt="Space">
            <!-- Recordar ponerlo por medio de los static -->
            <figcaption class="orbit-caption"></figcaption>
          </figure>
        </li>
        <li class="orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static 'img/FotoRepuestoSlide.jpg' %}" alt="Space">
            <figcaption class="orbit-caption"></figcaption>
          </figure>
        </li>
        <li class="orbit-slide">
            <figure class="orbit-figure">
              <img class="orbit-image" src="{% static 'img/FotoRepuestoSlideTres.jpg' %}" alt="Space">
              <figcaption class="orbit-caption"></figcaption>
            </figure>
          </li>
      </ul>

    </div>
  </div>
  <!-- fin de la imagen de portada -->

  <!-- bloque de bienvenida -->

  <div class="grid-x align-center margin-top"> 
    <!-- con el class=grid-x estamos indicando que trabaje con el foundation, recordar que es el framework de css -->
    <h1 class="cell large-8" style="font-size: 25px; text-align:center;">Bienvenido a CoyoSecure, una nueva forma de cuidar de ti y los tuyos</h1>
    <!-- recordar que el cell lo podremos usar para poder repartir las celdas de nuestra area de trabajo -->
    <div class="cell large-7">
        <div class="callout primary" style="text-align:center;">
            <h5>Experencia nueva para los usuario en su seguridad</h5>
            <p>Por medio del registro de tu IP en tiempo real podremos verificar tu estado de seguridad personal, para más información sigue el link.</p>
        </div>
    </div>
  </div>

  <!-- ----------------------------------------->

  <div class="grid-container margin-bottom ">
    <div class="grid-x grid-margin-x small-up-2 medium-up-3">
      <div class="cell fondo-medio-red border-radius">
        <div class="card border-radius">
          <img src="{% static 'img/ImagenCuatro.png' %}">
          <div class="card-section">
          <h4>Zona de Riesgo</h4>
            <p>Registra las zonas de riesgo, con ello, nos ayudas a conocer nuevas zonas para registrar y cuidar tu integridad personal.</p>
            <a class="button alert margen-botones" href="{% url 'ubicacion_app:zonas_all'%}">Zonas de Riesgo</a>
          </div>
        </div>
      </div>
      <div class="cell fondo-medio-green border-radius">
        <div class="card border-radius">
          <img src="{% static 'img/ubicacionTres.png' %}">
          <div class="card-section">
            <h4>Mi ubicación actual</h4>
            <p>Conprueba tu ubicación, con ello podrás comprobar que tu dirección IP funciona de manera correcta en la zona donde vives.</p>
            <a class="button success margen-botones" href="{% url 'ubicacion_app:ubicacion-actual'%}">Tu ubicación</a>
          </div>
        </div>
      </div>
      <div class="cell fondo-medio-gris border-radius">
        <div class="card border-radius">
          <img src="{% static 'img/ImagenSeis.png' %}">
          <div class="card-section">
            <h4>Registrar un delito</h4>
            <p>Registra los delitos cometidos en tu colonia, podrás registrar toda la información como imágenes, relato y videos.</p>
            <a class="button secondary margen-botones" href="#">Registra un delito</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/templates-generales/registroTotal.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Registro total de zonas{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="text-success">
  <div class="grid-x grid-margin-x align-center">
    <div class="cell small-12 medium-10 large-8">
      <h1 class="text-center">Lista de zonas por riesgo</h1>
      
      <form method="GET" class="grid-x grid-margin-x align-center">
        <div class="cell small-10 medium-7">
          <input type="text" id="kword" name="kword" placeholder="Buscar por Codiogo Postal" class="input-group-field">
        </div>
        <div class="cell small-2 medium-2">
          <button type="submit" class="button secondary expanded">Buscar</button>
        </div>
      </form>

      <!-- Cartas para las distintas zonas de seguridad en coyoacan -->
      <div class="grid-x grid-margin-x">
        {% for e in registro %}
        <div class="cell small-12 medium-6 large-6">
          <div class="card border-radius">
            <div class="card-divider tamanio-fuente-chica">
              <h5>{{ e.nombre_ciudad }}</h5>
            </div>
            <div class="card-section">

              {% if e.seguridad_zona == '0' %}
              <img src="{% static 'img/Seguro.png' %}" alt="Space">
              {% endif %}

              {% if e.seguridad_zona == '1' %}
              <img src="{% static 'img/Inseguro.png' %}" alt="Space">
              {% endif %}

              {% if e.seguridad_zona == '2' %}
              <img src="{% static 'img/Zona Delictiva.png' %}" alt="Space">
              {% endif %}

              <p><strong>CP: </strong> {{ e.codigo_postal }}</p>
              <p><strong>Colonia: </strong> {{ e.nombre_colonia }}</p>
              <p><strong>Nivel de Seguridad: </strong>{{e.get_seguridad_zona_display}}</p>
         
              <div class="text-center">
                <div class="button-group no-gaps">
                  <a href="{% url 'ubicacion_app:delitos-registros' e.codigo_postal %}" class="secondary button">Ver delitos</a>
                  <a href="{% url 'ubicacion_app:zona-modificada' e.codigo_postal %}" class="success button">Modificar Valores</a>
                  <a href="{% url 'ubicacion_app:detalles-ratero' e.codigo_postal %}" class="warning button">Ver delincuentes</a>
                </div>
              </div>
              
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      
      {% if is_paginated %} 
      <nav aria-label="Pagination" class="text-center">
        <ul class="pagination">
          {% if page_obj.has_previous %}
          <li class="pagination-previous">
            <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
          </li>
          {% endif %}
          
          {% for pagina in paginator.page_range %}
          {% if pagina == page_obj.number %}
          <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
          {% else %}
          <li><a href="?page={{ pagina }}">{{ pagina }}</a></li>
          {% endif %}
          {% endfor %}
          
          {% if page_obj.has_next %}
          <li class="pagination-next">
            <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
    </div>
  </div>
</div>


<div class="row grid-container">
  <div class="columns">
    <div class="orbit" role="region" aria-label="Favorite Text Ever" data-orbit>
      <ul class="orbit-container">
        <button class="orbit-previous" aria-label="previous"><span class="show-for-sr">Previous Slide</span>&#9664;</button>
        <button class="orbit-next" aria-label="next"><span class="show-for-sr">Next Slide</span>&#9654;</button>
        <li class="orbit-slide">
          <div class="docs-example-orbit-slide text-center">
            <!-- Recordar el uso de text-center para el centrado de botones -->
            <p><strong>Zona delictiva: </strong>Se caracterizan por una alta incidencia de crímenes y otros factorees que las hacen peligrosas para vivir o visitar. <strong>Como características principales tenemos: Alta tasa de criminalidad, pésima iluminación, ausencia de policía, infraestructura precaria.</strong></p>
            <a class="button alert centrar-botones" href="{% url 'ubicacion_app:zona_delictiva' %}">Zonas Delictivas</a>
          </div>
        </li>
        <li class="orbit-slide">
          <div class="docs-example-orbit-slide text-center">
            <p><strong>Zona insegura: </strong>Las zonas inseguras presentan una combinación de factores que pueden generar preocupación entre los residentes y visitantes. <strong>Como características principales tenemos: Moderada tasa de criminalidad, iluminación insuficiente, presencia de policia irregular.</strong></p>
            <a class="button warning" href="{% url 'ubicacion_app:zona_insegura' %}">Zonas Inseguras</a>   
          </div>
        </li>
        <li class="orbit-slide">
          <div class="docs-example-orbit-slide text-center">
            <p><strong>Zona segura: </strong>Una zona segura se catacteriza por varios factores que le hacen ideal para vivir y realizar actividades diarias con tranquiliad. <strong>Como características principales tenemos: Baja tasa de criminalidad, buena ilumnicación, presencia policial, comunidad activa.</strong></p>
            <a class="button success" href="{% url 'ubicacion_app:zona_segura' %}">Zonas Seguras</a>
          </div>
        </li>
      </ul>
      <nav class="orbit-bullets">
        <button class="is-active" data-slide="0"><span class="show-for-sr">First slide details.</span><span class="show-for-sr">Current Slide</span></button>
        <button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
        <button data-slide="2"><span class="show-for-sr">Third slide details.</span></button>
      </nav>
    </div>
  </div>
</div>

{% endblock content %}

templates/templates-generales/ubicacion.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Ubicación {% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="container grid-container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card border-0 shadow-lg">
                <div class="card-header bg-dark text-light text-center">
                    <h1 class="card-title mb-0">Ubicación actual</h1>
                </div>
                <div class="card-body">
                    {% if error %}
                    <div class="alert alert-danger text-center">
                        {{ error }}
                    </div>
                    {% elif not seguridad %}
                    <div class="text-center">
                        <p><strong>País:</strong> {{ data.country }}</p>
                        <p><strong>Latitud:</strong> {{ data.lat }}</p>
                        <p><strong>Longitud:</strong> {{ data.lon }}</p>
                    </div>
                    <hr>
                    <h3 class="card-title text-center">Más detalles</h3>
                    <div class="text-center">
                        <p><strong>Código de país:</strong> {{ data.countryCode }}</p>
                        <p><strong>Zona horaria:</strong> {{ data.timezone }}</p>
                        <p><strong>Código Postal:</strong> {{ data.zip }}</p> 
                    </div>
                    <div id="map" style="height: 400px;"></div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    {% if not seguridad %}
    <script>
        var map = L.map('map').setView([{{ data.lat }}, {{ data.lon }}], 13);
    
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);
    
        L.marker([{{ data.lat }}, {{ data.lon }}]).addTo(map)
            .bindPopup('Ubicación aproximada')
            .openPopup();
    </script>
    {% endif %}

    <div class="callout primary grid-container text-center">
        <h5>Conoce tu estado de seguridad</h5>
        <p>Por medio de esta función podrás conocer el estado de seguridad en el que te encuentras dependiendo tu ubicación. Puedes ingresar tu Codigo Postal en tiempo real que se encuentra en la parte superior <strong>o puedes ingresar manualmente tu código postal actual.</strong></p>
        <form method="get" action="{% url 'ubicacion_app:estado-seguridad' %}">
            <label for="codigo_postal">Ingrese su código postal:</label>
            <input type="text" id="codigo_postal" name="codigo_postal" required>
            <button type="submit" class="alert button text-center">Conocer mi estado actual de seguridad</button>
        </form>
    </div>

    {% if seguridad == 'segura' %}
    <div class="callout success text-center">
        <h5><strong>Te encuentras en una zona segura.</strong></h5>
        <p>Tu seguridad no se encuentra comprometida, sin embargo no dejes de prestar atención a tu alrededor</p>
        <p>La zona es: <strong>{{ seguridad }}</strong></p>

        <img src="{% static 'img/Seguro.png' %}" alt="Space">
    </div>

    {% elif seguridad == 'insegura' %}
    
    <div class="callout warning text-center">
        <h5><strong>Te encuentras en una insegura.</strong></h5>
        <p>Tu seguridad se encuentra comprometida, no dejes de prestar atención a tu alrededor</p>
        <p>La zona es: <strong>{{ seguridad }}</strong></p>

        <img src="{% static 'img/Inseguro.png' %}" alt="Space">
    </div>
    
    {% elif seguridad == 'zona delictiva' %}
    
    <div class="callout alert text-center">
        <h5><strong>Te encuentras en una zona delictiva.</strong></h5>
        <p>Tu seguridad se encuentra altamente comprometida, no dejes de prestar atención a tu alrededor y supervisa tus movimientos.</p>
        <p>La zona es: <strong>{{ seguridad }}</strong></p>

        <img src="{% static 'img/Zona Delictiva.png' %}" alt="Space">
    </div>
    
    {% endif %}

</div>

{% endblock content %}