geolocation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('location.urls'))
]

location/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static  


app_name = "ubicacion_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name='Inicio'),
    path('ubicacion_actual/', views.ubicacion, name='ubicacion-actual'),
    path('registros-delitos/',views.ListAllZonas.as_view(),name='zonas_all'),
    path('registros-segura/', views.ListSegura.as_view(), name='zona_segura'),
    path('registros-insegura/', views.ListInsegura.as_view(), name='zona_insegura'),
    path('registros-delictiva/', views.ListDelictiva.as_view(), name='zona_delictiva'),
    # Clase para poder ver los delitos
    path("ver-delitos/<str:codigo_postal>/", views.DelitosPorCodigoPostalView.as_view(), name="delitos-registros"),
    path("update-zona/<str:codigo_postal>/", views.ZonaModUpdateView.as_view(), name = 'zona-modificada'),
    path("estado-seguridad/", views.estado_seguridad, name='estado-seguridad'),
    # Formulario para registrar un delito
    path('registrar-delito/', views.RegistrarDelitoView.as_view(), name='registrar_delito'),
    path('borrar-delito/<int:pk>/', views.DelitoDeleteView.as_view(), name="borrar-delito"), 
    path('registro-ratero/', views.RegistrarRateroView.as_view(), name='agregar-ratero'),
    path('ver-ratero/<str:codigo_postal>/', views.DelincuentesPorCodigoPostalView.as_view(), name='detalles-ratero'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

location/models.py
from django.db import models

# Create your models here.

class Ubicacion(models.Model):

    SEGURIDAD_CHOICES = [
        ('0', 'segura'),
        ('1', 'insegura'),
        ('2', 'zona delictiva'),
    ]
    
    codigo_postal = models.CharField("Código postal", max_length=10, unique=False)
    nombre_ciudad = models.CharField("Nombre de la ciudad", max_length=50)
    nombre_colonia = models.CharField("Nombre de la colonia", max_length=70)
    seguridad_zona = models.CharField(
        "Seguridad de la zona", 
        max_length=1,
        choices=SEGURIDAD_CHOICES, 
        default='0'
    )

    class Meta:
        verbose_name = "Dato de seguimiento"
        verbose_name_plural = "Datos de seguimiento"

    def __str__(self):
        return self.codigo_postal


class Delito(models.Model):
    TIPO_DELITO = [
        ('0', 'robo'),
        ('1', 'asalto'),
        ('2', 'abuso'),
        ('3', 'venta de drogas'),
        ('4', 'homicidio'),
        ('5', 'secuestro'),
        ('6', 'feminicidio'),
    ]
    
    codigop_delito = models.ForeignKey(Ubicacion, on_delete=models.CASCADE) 
    delegacion_delito = models.CharField("Delegación del delito", max_length=30)
    calle_delito = models.CharField("Calle del delito", max_length=30)
    colonia_delito = models.CharField("Colonia del delito", max_length=30)
    tipo_delito = models.CharField(
        "Tipo de Delito", 
        max_length=1,
        choices=TIPO_DELITO, 
        default='0'
    )
    
    descripcion = models.TextField("Descripción del delito", blank=True) #La persona podrá agregar una descripción del delito.

    class Meta:
        verbose_name = "Registro de delito"
        verbose_name_plural = "Registros de delitos"

    def __str__(self):
        return self.codigop_delito.codigo_postal

class Delincuente(models.Model):

    codigop_delincuente = models.ForeignKey(Ubicacion,on_delete=models.CASCADE) 
    nombre_delincuente = models.CharField("Nombre del delincuente", max_length=40)
    proceso = models.CharField("¿Se encuentra en proceso el delincuente?", max_length=100)
    avatar = models.ImageField("Imagen del delincuente",upload_to='media/delincuente', blank = True, null = True) #Aqui se guardará la IMAGEN.
    descripcion_delincuente = models.TextField("Describe las características del delincuente", blank=True) #La persona podrá agregar una descripción del delito.
   
    class Meta:
        verbose_name = "Datos de delicuente"
        verbose_name_plural = "Datos de los delincuentes"

    def __str__(self):
        return self.codigop_delincuente.codigo_postal   

templates/infoDelincuente/delincuente_form.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Registrar Delito{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="callout warning">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell small-12 medium-10 large-8">
            <h2>Agregar Delincuente</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="submit success button">Guardar</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/infoDelincuente/detalle_delito.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Detalles del Ratero{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="text-center">
    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center">
            {% for ratero in delincuentes %}
            <div class="cell small-12 medium-6 large-7">
                <div class="card border-radius">
                    <div class="card-divider tamanio-fuente-chica">
                        <h5><strong>Detalles del delincuente</strong></h5>
                    </div>
                    <div class="card-section">
                        <img src="{{ ratero.avatar.url }}" alt="{{ ratero.nombre_delincuente }}">
                        <p><strong>Nombre: </strong> {{ ratero.nombre_delincuente }}</p>
                        <p><strong>En proceso: </strong> {{ ratero.proceso }}</p>
                        <div class="callout secondary">
                            <h3>Características del delincuente</h3>
                            <p>{{ratero.descripcion_delincuente}}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <p>No hay delincuentes registrados en esta zona.</p>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

templates/infoDelincuente/detalle_especifico.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Detalles del Ratero{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container text-center">

    <div class="callout alert text-center">
        <div class="grid-x grid-margin-x align-center">
            <div class="cell small-12 medium-10 large-6">

                <div class="callout primary">

                    <h2>Detalles del Ratero</h2>
                
                    {% for ratero in delincuentes %}
                        <img src="{{ ratero.avatar.url }}" alt="{{ ratero.nombre_delincuente }}">
                        <p><strong>Nombre:</strong> {{ ratero.nombre_delincuente }}</p>
                        <p><strong>En Proceso:</strong> {{ ratero.proceso }}</p>
                        
                        <h3>Delitos Asociados</h3>
                        <ul>
                            {% for delito in ratero.codigop_delincuente.delito_set.all %}
                                <p>{{ delito.colonia_delito }} - {{ delito.get_tipo_delito_display }}</p>
                                <p>{{delito.descripcion}}</p>
                            {% endfor %}
                        </ul>                
                    {% empty %}
                        <p>No hay delincuentes registrados en esta zona.</p>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>

</div>



{% endblock content %}