geolocation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('location.urls'))
]

location/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static  


app_name = "ubicacion_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name='Inicio'),
    path('ubicacion_actual/', views.ubicacion, name='ubicacion-actual'),
    path('registros-delitos/',views.ListAllZonas.as_view(),name='zonas_all'),
    path('registros-segura/', views.ListSegura.as_view(), name='zona_segura'),
    path('registros-insegura/', views.ListInsegura.as_view(), name='zona_insegura'),
    path('registros-delictiva/', views.ListDelictiva.as_view(), name='zona_delictiva'),
    # Clase para poder ver los delitos
    path("ver-delitos/<str:codigo_postal>/", views.DelitosPorCodigoPostalView.as_view(), name="delitos-registros"),
    path("update-zona/<str:codigo_postal>/", views.ZonaModUpdateView.as_view(), name = 'zona-modificada'),
    path("estado-seguridad/", views.estado_seguridad, name='estado-seguridad'),
    # Formulario para registrar un delito
    path('registrar-delito/', views.RegistrarDelitoView.as_view(), name='registrar_delito'),
    path('borrar-delito/<int:pk>/', views.DelitoDeleteView.as_view(), name="borrar-delito"), 
    path('registro-ratero/', views.RegistrarRateroView.as_view(), name='agregar-ratero'),
    path('ver-ratero/<str:codigo_postal>/', views.DelincuentesPorCodigoPostalView.as_view(), name='detalles-ratero'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<!-- Aqui vamos a colocar todo lo que se pueda repetir entre cada uno de los templates -->
<!-- Recordar que los includes son partes estáticas de nuestra página web en Django que se repetira varias veces dentro de nuestro codigo -->

<!-- En este caso es el header o barra de busqueda -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/generales.css' %}">
</head>
<body>
  
  <div class="top-bar margen-botones margin-bottom padding-header">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">CoyoSecure</li>
        
        <li>
          <a class="button warning margen-botones border-radius" href="{% url 'ubicacion_app:Inicio'%}">Inicio</a>
          <!-- Recordar que esta en paginacion y las urls se escriben de la siguiente forma: /?page=4 -->
          <!-- Esta es la forma optima para relacionar URLS en los estaticos -->
        </li>
        <li><a class="button alert margen-botones border-radius" href="{% url 'ubicacion_app:zonas_all'%}">Zonas de Riesgo</a></li>
        <li><a class="button success margen-botones border-radius" href="{% url 'ubicacion_app:ubicacion-actual'%}">Verifica tu seguridad</a></li>
        <!-- Recurerda que este boton esta vinculado a un formulario -->
        <li><a class="button secondary margen-botones border-radius" href="{% url 'ubicacion_app:registrar_delito' %}">Registra un delito</a></li>
        <li><a class="button secondary margen-botones border-radius" href="{% url 'ubicacion_app:agregar-ratero' %}">Denuncia al ratero</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        {% comment %} Recordar colocar el apartado de rateros en el header, conectar el HTML con los demás funcionamientos . {% endcomment %}
        <li><a class="button border-radius" href="https://www.ssc.cdmx.gob.mx/">Policia de la CDMX</a></li>
      </ul>
    </div>
  </div>
  
</body>
</html>